"""empty message

Revision ID: 99664d769ef9
Revises: 6acc6a778524
Create Date: 2023-04-10 20:58:03.751255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99664d769ef9'
down_revision = '6acc6a778524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms_list',
    sa.Column('roomid', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=60), nullable=True),
    sa.Column('room_name', sa.String(length=30), nullable=True),
    sa.Column('room_type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('roomid')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('rooms_list')
    # ### end Alembic commands ###
